version: '3.1'

services:
  noti_backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: noti_backend
    restart: always
    volumes:
      - ./backend:/app
    #depends_on:
    #  - "mongodb"
    ports:
      - 8080:8080
    env_file:
      - .env

  noti_frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: noti_frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    env_file:
      - .env
